# Generated by Django 4.2.6 on 2023-12-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_answer_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='context',
            field=models.TextField(),
        ),
    ]
